version: 1.0.{build}-alpha
configuration: Release
os: Visual Studio 2015
install:
- dnvm upgrade -r clr
- dnu restore
before_build:
- nuget restore
build:
  verbosity: minimal
test_script:
- dnx -p test\SharpSyslogServer.Tests\project.json test
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/de4ffe5142ae19358610
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true