version: 1.0.{build}-alpha
configuration: Release
os: Visual Studio 2015
install:
- dotnet restore
build:
  verbosity: minimal
test_script:
- dotnet test SharpSyslogServer.Tests\project.json
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/de4ffe5142ae19358610
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true